2017-03-20T15:21:25.493Z - debug: '/projects/da4b09c7-73a7-4027-ac2d-5fed6d409acf/.smc-DEBUG' does not exist; minimal logging
2017-03-20T15:21:25.498Z - debug: writing info.json
2017-03-20T15:21:25.519Z - debug: initializing secret token
2017-03-20T15:21:25.519Z - debug: read the secret token file...
2017-03-20T15:21:25.520Z - debug: create '/projects/da4b09c7-73a7-4027-ac2d-5fed6d409acf/.smc/secret_token'
2017-03-20T15:21:25.521Z - debug: got secret token = S8OpZ/noJsr1y6+DMPC9AvxEsyLR/0mHJlClKZmM+yam9Bag+MNW+VO1n6KQmgv7ftlbpRbzvU6iyHLaIR4cBmI5R8PRBgQGSD3bb0PyQjSeVUEjCJ8ULtOZ+7RdTWuJ2Yc+90qc6F2s+VImnTTTj2kBtuBMvJWwfIXJoxAGtvM=
2017-03-20T15:21:25.521Z - info: starting tcp server: project <--> hub...
2017-03-20T15:21:25.529Z - info: tcp_server listening 0.0.0.0:33088
2017-03-20T15:21:25.539Z - info: starting raw http server...
2017-03-20T15:21:26.055Z - info: raw server: port=36993, host='10.240.0.31', base='/da4b09c7-73a7-4027-ac2d-5fed6d409acf/raw/'
2017-03-20T15:21:26.059Z - debug: Successfully started servers.
2017-03-20T15:22:13.768Z - debug: received new connection
2017-03-20T15:22:13.818Z - debug: hello from hub -- sending back our version = 1489935488
2017-03-20T15:22:13.918Z - debug: open_syncstrings: 0; recent_syncstrings: 1
2017-03-20T15:22:14.777Z - debug: open_syncstrings: 1; recent_syncstrings: 1
2017-03-20T15:30:19.577Z - debug: received new connection
2017-03-20T15:30:19.615Z - debug: hello from hub -- sending back our version = 1489935488
2017-03-20T15:30:19.802Z - debug: open_syncstrings: 1; recent_syncstrings: 2
2017-03-20T15:30:19.828Z - debug: open_syncstrings: 2; recent_syncstrings: 2
2017-03-20T15:30:20.054Z - debug: BUG ****************************************************************************
2017-03-20T15:30:20.054Z - debug: Uncaught exception: TypeError: _this.get_doc(...).slice is not a function
2017-03-20T15:30:20.056Z - debug: TypeError: _this.get_doc(...).slice is not a function
    at Object._this._client.path_exists.cb (/usr/lib/node_modules/smc-util/syncstring.coffee:1515:118)
    at /usr/lib/node_modules/smc-project/client.coffee:606:18
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)

2017-03-20T15:30:20.056Z - debug: BUG ****************************************************************************
Trace
    at process.<anonymous> (/usr/lib/node_modules/smc-project/local_hub.coffee:341:22)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:254:26)

2017-03-20T15:30:23.049Z - debug: received new connection
2017-03-20T15:30:23.087Z - debug: hello from hub -- sending back our version = 1489935488
2017-03-20T15:30:37.527Z - debug: jupyter_port: undefined
2017-03-20T15:30:37.527Z - debug: jupyter_port: checking jupyter status
2017-03-20T15:30:37.895Z - debug: jupyter_port: got status={"status":"stopped"}
2017-03-20T15:30:37.895Z - debug: jupyter_port: not running, so start it running
2017-03-20T15:30:39.515Z - debug: jupyter_port: after starting, got status=undefined
2017-03-20T15:30:39.515Z - debug: jupyter_port: finished; (err=error parsing smc-jupyter startup output -- SyntaxError: Unexpected token / in JSON at position 0, {misc.to_json(out)}); now sending resp
2017-03-20T15:30:40.340Z - debug: jupyter_port: undefined
2017-03-20T15:30:40.340Z - debug: jupyter_port: checking jupyter status
2017-03-20T15:30:41.013Z - debug: jupyter_port: got status={"status":"running","base":" --NotebookApp.base_url=/da4b09c7-73a7-4027-ac2d-5fed6d409acf/port/jupyter/ --NotebookApp.base_kernel_url=/da4b09c7-73a7-4027-ac2d-5fed6d409acf/port/jupyter/ ","pid":7659,"port":15130}
2017-03-20T15:30:41.013Z - debug: jupyter_port: already running; nothing more to do
2017-03-20T15:30:41.014Z - debug: jupyter_port: finished; (err=null); now sending resp
2017-03-20T15:33:01.815Z - debug: jupyter_port: undefined
2017-03-20T15:33:01.815Z - debug: jupyter_port: checking jupyter status
2017-03-20T15:33:02.179Z - debug: jupyter_port: got status={"status":"running","base":" --NotebookApp.base_url=/da4b09c7-73a7-4027-ac2d-5fed6d409acf/port/jupyter/ --NotebookApp.base_kernel_url=/da4b09c7-73a7-4027-ac2d-5fed6d409acf/port/jupyter/ ","pid":7659,"port":15130}
2017-03-20T15:33:02.179Z - debug: jupyter_port: already running; nothing more to do
2017-03-20T15:33:02.179Z - debug: jupyter_port: finished; (err=null); now sending resp
2017-03-20T15:33:02.224Z - debug: open_syncstrings: 2; recent_syncstrings: 3
2017-03-20T15:33:02.362Z - debug: BUG ****************************************************************************
2017-03-20T15:33:02.362Z - debug: Uncaught exception: TypeError: _this.get_doc(...).slice is not a function
2017-03-20T15:33:02.362Z - debug: TypeError: _this.get_doc(...).slice is not a function
    at Object._this._client.path_exists.cb (/usr/lib/node_modules/smc-util/syncstring.coffee:1515:118)
    at /usr/lib/node_modules/smc-project/client.coffee:606:18
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)

2017-03-20T15:33:02.362Z - debug: BUG ****************************************************************************
Trace
    at process.<anonymous> (/usr/lib/node_modules/smc-project/local_hub.coffee:341:22)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:254:26)

2017-03-20T15:33:02.365Z - debug: open_syncstrings: 3; recent_syncstrings: 3
2017-03-20T15:33:37.155Z - debug: jupyter_port: undefined
2017-03-20T15:33:37.155Z - debug: jupyter_port: checking jupyter status
2017-03-20T15:33:37.757Z - debug: jupyter_port: got status={"status":"running","base":" --NotebookApp.base_url=/da4b09c7-73a7-4027-ac2d-5fed6d409acf/port/jupyter/ --NotebookApp.base_kernel_url=/da4b09c7-73a7-4027-ac2d-5fed6d409acf/port/jupyter/ ","pid":7659,"port":15130}
2017-03-20T15:33:37.757Z - debug: jupyter_port: already running; nothing more to do
2017-03-20T15:33:37.758Z - debug: jupyter_port: finished; (err=null); now sending resp
2017-03-20T15:33:39.491Z - debug: open_syncstrings: 3; recent_syncstrings: 4
2017-03-20T15:33:39.570Z - debug: open_syncstrings: 4; recent_syncstrings: 4
2017-03-20T15:33:39.633Z - debug: BUG ****************************************************************************
2017-03-20T15:33:39.633Z - debug: Uncaught exception: TypeError: _this.get_doc(...).slice is not a function
2017-03-20T15:33:39.633Z - debug: TypeError: _this.get_doc(...).slice is not a function
    at Object._this._client.path_exists.cb (/usr/lib/node_modules/smc-util/syncstring.coffee:1515:118)
    at /usr/lib/node_modules/smc-project/client.coffee:606:18
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)

2017-03-20T15:33:39.633Z - debug: BUG ****************************************************************************
Trace
    at process.<anonymous> (/usr/lib/node_modules/smc-project/local_hub.coffee:341:22)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:254:26)

2017-03-20T15:33:53.355Z - debug: open_syncstrings: 4; recent_syncstrings: 5
2017-03-20T15:33:53.458Z - debug: open_syncstrings: 5; recent_syncstrings: 5
2017-03-20T15:33:53.555Z - debug: BUG ****************************************************************************
2017-03-20T15:33:53.555Z - debug: Uncaught exception: TypeError: Cannot read property 'slice' of undefined
2017-03-20T15:33:53.555Z - debug: TypeError: Cannot read property 'slice' of undefined
    at Object._this._client.path_exists.cb (/usr/lib/node_modules/smc-util/syncstring.coffee:1515:117)
    at /usr/lib/node_modules/smc-project/client.coffee:606:18
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)

2017-03-20T15:33:53.555Z - debug: BUG ****************************************************************************
Trace
    at process.<anonymous> (/usr/lib/node_modules/smc-project/local_hub.coffee:341:22)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:254:26)

2017-03-20T15:35:28.455Z - debug: handle_save_blob_message: da39a3ee-5e6b-44b0-9325-5bfef9560189
2017-03-20T15:35:28.567Z - debug: received new connection
2017-03-20T15:35:28.607Z - debug: connect_to_session -- type='console'
2017-03-20T15:35:28.608Z - debug: get_session: console session 0d3c756c-87ed-46c4-9d6f-4227c1a0d2bf
2017-03-20T15:35:28.608Z - debug: console session not yet created -- put on stack
2017-03-20T15:35:28.608Z - debug: console session does not exist or is not running, so we make a new session
2017-03-20T15:35:28.609Z - debug: couldn't determine console server port; probably console server not running -- try restarting it
2017-03-20T15:35:28.610Z - debug: restart_console_server: undefined
2017-03-20T15:35:28.610Z - debug: restart_console_server: "restarting daemon"
2017-03-20T15:35:28.610Z - debug: restart_console_server: "remove port_file=/projects/da4b09c7-73a7-4027-ac2d-5fed6d409acf/.smc/console_server/console_server.port"
2017-03-20T15:35:28.611Z - debug: restart_console_server: "restart console server"
2017-03-20T15:35:29.409Z - debug: restart_console_server: "wait a little to see if /projects/da4b09c7-73a7-4027-ac2d-5fed6d409acf/.smc/console_server/console_server.port appears, and if so read it and return port"
2017-03-20T15:35:31.709Z - debug: restart_console_server: "finished trying to restart console_server"
2017-03-20T15:35:31.709Z - debug: restarted console server, then got port = 35870
2017-03-20T15:35:31.709Z - debug: console: Got port -- now create the new session
2017-03-20T15:35:31.710Z - debug: _new_session: defined by {"event":"connect_to_session","id":"dd536d13-cf86-493c-a3e6-5b217bc296ae","type":"console","project_id":"da4b09c7-73a7-4027-ac2d-5fed6d409acf","session_uuid":"0d3c756c-87ed-46c4-9d6f-4227c1a0d2bf","params":{"command":"bash","path":"./","filename":"2017-03-20-124019.term"}}
